apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-app-injection
  namespace: server
data:
  config: |
    Gabriel, Fulano, Ciclano

    Here we can pass multiple types of files/variables. For now,
    i am applying this text with the members of my family.txt