apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  annotations: 
    kubernetes.io/ingress.class: "nginx"
  labels:
    name: myingress
spec:
  rules:
  - host: kind-cluster.example
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: go-http-app-service
            port: 
              number: 80


