apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
  namespace: server
spec:
  resources:
    requests:
      storage: 1Gi
  #volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
