# Service Accont
apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-service-account
---
# Role 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: server
rules:
- apiGroups: [""] # "" Indicates the Core API group
  resources: ["services"] # We are allowing Services
  verbs: ["get", "watch", "list"] # We can do list operations on Services
---
# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: server
subjects:
- kind: ServiceAccount
  name: server-service-account # ServiceAccount name created above
  namespace: server # ServiceAccount namespace
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
