apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: server
rules:
- apiGroups: [""] # "" Indicates the Core API group
  resources: ["services"] # We are allowing Services
  verbs: ["get", "watch", "list"] # We can do list operations on Services